[package]
name = "warp_gui"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdlimit = "0.2"
dioxus = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
dioxus-html = { version = "0.2.1" }
fermi = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
dioxus-core = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
sir = { git = "https://github.com/Satellite-im/sir", features = ["dioxus"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
anyhow = "1.0"
once_cell = "1.13"
copypasta = "0.8.1"
dioxus-toast = { git = "https://github.com/Satellite-im/dioxus-toast", features = ["desktop"] }
#dioxus-toast = { version = "0.1.5"}
dioxus-heroicons = { git = "https://github.com/Satellite-im/dioxus-heroicons" }
clap = { version = "3.2", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
chrono-humanize = "0.2.2"

warp = { git = "https://github.com/Satellite-im/Warp", branch = "warp/config-change"}
warp-mp-ipfs = { git = "https://github.com/Satellite-im/Warp", branch = "warp/config-change" }
warp-rg-ipfs = { git = "https://github.com/Satellite-im/Warp", branch = "warp/config-change" }


[build-dependencies]
glob = "0.3.0"
rsass = "0.25.2"
