[package]
name = "warp_gui"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
#dioxus = { version = "0.2.4" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
dioxus-html = {version = "0.2.1"}
fermi = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus", branch = "master"}
dioxus-core = { git = "https://github.com/DioxusLabs/dioxus", branch = "master" }
sir = { git = "https://github.com/Satellite-im/sir", features = ["dioxus"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
anyhow = "1.0"
once_cell = "1.13"
copypasta = "0.8.1"
dioxus-toast = { git = "https://github.com/Satellite-im/dioxus-toast" }
dioxus-heroicons = { git = "https://github.com/Satellite-im/dioxus-heroicons" }
clap = { version = "3.2", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
chrono-humanize = "0.2.2"

warp = { git = "https://github.com/Satellite-im/Warp", branch = "warp/mp-ipfs-minor-change-2" }
warp-mp-ipfs = { git = "https://github.com/Satellite-im/Warp", branch = "warp/mp-ipfs-minor-change-2" }
warp-rg-ipfs = { git = "https://github.com/Satellite-im/Warp", branch = "warp/mp-ipfs-minor-change-2" }


[build-dependencies]
glob = "0.3.0"
rsass = "0.25.2"
#webkit2gtk-sys = "^0.18.0"
#wry = "^0.19.0"
