[general]
theme = "default"

[privacy]
satellite_sync_nodes = true
safer_file_scanning = true

[audiovideo]
noise_suppression = false

[extensions]
enable = false

[developer]
developer_mode = false
cache_dir = ".warp"
