# Satellite Global Ban List
# You can choose to modify or remove this ban list but we have found the following accounts to be dangerous for our community to interact with.
# We respect your right to choose so please feel free to modify this list, with the understanding that after doing so, Satellite no longer guarantees the safety, reliability, or trustworthiness of the content listed on the platform. 

[communities]

[users]
