# Satellite Global Ban List
# You can choose to modify or remove this ban list but we have found the following accounts to be dangerous for our community to interact with.
# We respect your right to choice so please feel free to modify this list, with the understanding that after doing so, Satellite no lonter garuntees the saftey, reliability, or trustworthyness of the content listed on the platform. 

[communities]

[users]
