version: 2.1
jobs:
  test_ubuntu:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: sudo apt install protobuf-compiler
      - run:
          name: Test
          command: cargo test

  build_ubuntu:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: sudo apt install protobuf-compiler
      - run:
          name: Build Binary
          command: cargo build --release
      - run:
          name: Compress Artifacts (Bin)
          command: zip -r bin.zip target/release/warp_gui
      - store_artifacts:
          path: bin.zip
          destination: /ubuntu/bin.zip
      - store_artifacts:
          path: /ubuntu

  test_macos:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - run: brew update
      - run: brew install protobuf
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: cargo --version
      - run: rustup default stable
      - run:
          name: Run Tests
          command: cargo test

  build_macos:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - run: brew update
      - run: brew install protobuf
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: cargo --version
      - run: rustup default stable
      - run:
          name: Make Bin
          command: make binary
      - run:
          name: Make DMG
          command: make dmg
      - run:
          name: Make .app
          command: make app
      - run:
          name: Compress Artifacts (App)
          command: zip -r app.zip target/release/macos/WarpGUI.app
      - run:
          name: Compress Artifacts (DMG)
          command: zip -r dmg.zip target/release/macos/WarpGUI.DMG
      - run:
          name: Compress Artifacts (Bin)
          command: zip -r bin.zip target/release/warp_gui
      - store_artifacts:
          path: app.zip
          destination: /macos/app.zip
      - store_artifacts:
          path: dmg.zip
          destination: /macos/dmg.zip
      - store_artifacts:
          path: bin.zip
          destination: /macos/bin.zip
      - store_artifacts:
          path: /macos

workflows:
  test_and_build:
    jobs:
      - test_macos
      - test_ubuntu
      - build_macos:
          requires:
            - test_macos
      - build_ubuntu:
          requires:
            - test_ubuntu