version: 2.1
jobs:
  test_linux:
    docker:
      - image: circleci/rust
    parameters:
      version:
        default: stable
        description: Version of Rust to install and default to.
        type: string
    steps:
      - checkout
      - run:
          command: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh\nchmod +x rustup.sh\n./rustup.sh -y\n\nsource \"$HOME\"/.cargo/env\n\nif [ \"$RUST_VERSION\" != \"stable\" ]; then\n\trustup toolchain install \"$RUST_VERSION\"\n\trustup default \"$RUST_VERSION\"\nfi\n"
          environment:
            RUST_VERSION: <<parameters.version>>
          name: Install Rustup
      - run:
          command: echo 'source $HOME/.cargo/env' >> $BASH_ENV
          name: Setting up Cargo environment in $BASH_ENV
      - run:
          name: Test
          command: rustup run stable cargo test

  build_linux:
    docker:
      - image: circleci/rust
    parameters:
      version:
        default: stable
        description: Version of Rust to install and default to.
        type: string
    steps:
      - checkout
      - run:
          command: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh\nchmod +x rustup.sh\n./rustup.sh -y\n\nsource \"$HOME\"/.cargo/env\n\nif [ \"$RUST_VERSION\" != \"stable\" ]; then\n\trustup toolchain install \"$RUST_VERSION\"\n\trustup default \"$RUST_VERSION\"\nfi\n"
          environment:
            RUST_VERSION: <<parameters.version>>
          name: Install Rustup
      - run:
          name: Build Binary
          command: rustup run stable cargo build --release
      - run:
          name: Compress Artifacts (Bin)
          command: zip -r bin.zip target/release/warp_gui

  test_macos:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - run: brew update
      - run: brew install protobuf
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: cargo --version
      - run: rustup default stable
      - run:
          name: Run Tests
          command: cargo test
      - store_artifacts:
          path: bin.zip
          destination: /linux/bin.zip
      - store_artifacts:
          path: /linux

  build_macos:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - run: brew update
      - run: brew install protobuf
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: cargo --version
      - run: rustup default stable
      - run:
          name: Make Bin
          command: make binary
      - run:
          name: Make DMG
          command: make dmg
      - run:
          name: Make .app
          command: make app
      - run:
          name: Compress Artifacts (App)
          command: zip -r app.zip target/release/macos/WarpGUI.app
      - run:
          name: Compress Artifacts (DMG)
          command: zip -r dmg.zip target/release/macos/WarpGUI.DMG
      - run:
          name: Compress Artifacts (Bin)
          command: zip -r bin.zip target/release/warp_gui
      - store_artifacts:
          path: app.zip
          destination: /macos/app.zip
      - store_artifacts:
          path: dmg.zip
          destination: /macos/dmg.zip
      - store_artifacts:
          path: bin.zip
          destination: /macos/bin.zip
      - store_artifacts:
          path: /macos

workflows:
  test_and_build:
    jobs:
      - test_macos
      - test_linux
      - build_macos:
          requires:
            - test_macos
      - build_linux:
          requires:
            - test_linux