
version: 2.1
jobs:
  test_macos:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - run: brew update
      - run: brew install protobuf
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: cargo --version
      - run: rustup default stable
      - run:
          name: Run Tests
          command: cargo test

  build_macos:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - run: brew update
      - run: brew install protobuf
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: cargo --version
      - run: rustup default stable
      - run:
          name: Make Bin
          command: cargo build
      - run:
          name: Make DMG
          command: make dmg
      - run:
          name: Make .app
          command: make app
      - run:
          name: Compress Artifacts (App)
          command: zip -r app.zip target/release/macos/WarpGUI.app
      - run:
          name: Compress Artifacts (DMG)
          command: zip -r dmg.zip target/release/macos/WarpGUI.DMG
      - run:
          name: Compress Artifacts (Bin)
          command: zip -r bin.zip target/release/warp_gui
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/artifacts/
          path: app.zip
          destination: App
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/artifacts/
          path: dmg.zip
          destination: DMG
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/artifacts/
          path: bin.zip
          destination: Bin

workflows:
  test_and_build:
    jobs:
      - test_macos
      - build_macos:
          requires:
            - test_macos