version: 2.1
jobs:
  build_binary:
    docker:
      - image: 'cimg/rust:1.50.0'
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: cargo test
      - run:
          name: Build Bin
          command: cargo build
      - run:
          name: Build Bundle
          command: cargo bundle
  build_macos:
    macos:
      xcode: 14
    steps:
      - checkout
      - run: brew update
      - run: brew install protobuf
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run:
          name: Make Bin
          command: cargo build
      - run:
          name: Make DMG
          command: make dmg
      - run:
          name: Make .app
          command: make app
