
version: 2.1
orbs:
  rust: circleci/rust@1.6.0
jobs:
  test_linux:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Test
          command: rustup run stable cargo test
  build_linux:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Build Binary
          command: rustup run stable cargo build --release
      - run:
          name: Compress Artifacts (Bin)
          command: zip -r bin.zip target/release/warp_gui

  test_macos:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - run: brew update
      - run: brew install protobuf
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: cargo --version
      - run: rustup default stable
      - run:
          name: Run Tests
          command: cargo test
      - store_artifacts:
          path: bin.zip
          destination: /linux/bin.zip
      - store_artifacts:
          path: /linux

  build_macos:
    macos:
      xcode: 14.0
    steps:
      - checkout
      - run: brew update
      - run: brew install protobuf
      - run: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - run: source ~/.cargo/env
      - run: cargo --version
      - run: rustup default stable
      - run:
          name: Make Bin
          command: make binary
      - run:
          name: Make DMG
          command: make dmg
      - run:
          name: Make .app
          command: make app
      - run:
          name: Compress Artifacts (App)
          command: zip -r app.zip target/release/macos/WarpGUI.app
      - run:
          name: Compress Artifacts (DMG)
          command: zip -r dmg.zip target/release/macos/WarpGUI.DMG
      - run:
          name: Compress Artifacts (Bin)
          command: zip -r bin.zip target/release/warp_gui
      - store_artifacts:
          path: app.zip
          destination: /macos/app.zip
      - store_artifacts:
          path: dmg.zip
          destination: /macos/dmg.zip
      - store_artifacts:
          path: bin.zip
          destination: /macos/bin.zip
      - store_artifacts:
          path: /macos

workflows:
  test_and_build:
    jobs:
      - test_macos
      - build_macos:
          requires:
            - test_macos