name: Move Tickets to PR Open Column

on:
  pull_request:
    types: [opened]

jobs:
  move-tickets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Issue ID
        run: |
          # Extract the issue ID from the pull request description
          # The issue ID is expected to be in the format "#<issue-number>"
          PR=$(curl -H "Authorization: token $GITHUB_TOKEN" -X GET "https://api.github.com/repos/Satellite-im/Uplink/pulls/$GITHUB_EVENT_ID")
          ISSUE_ID=$(echo "$PR" | jq -r '.body' | grep -o "#[0-9]*")
          # Remove the "#" character from the issue ID
          ISSUE_ID=${ISSUE_ID:1}

      - name: Get PR Open Column ID
        run: |
          # Get the list of columns for the project
          COLUMNS=$(curl -H "Authorization: token $GITHUB_TOKEN" -X GET "https://api.github.com/repos/Satellite-im/Uplink/projects/4/columns")
          # Parse the response using jq to find the ID of the column with the name "PR Open"
          COLUMN_ID=$(echo "$COLUMNS" | jq -r '.[] | select(.name == "PR Open") | .id')

      - name: Move Issue to PR Open Column
        run: |
          # Move the issue to the PR Open column
          curl -H "Authorization: token $GITHUB_TOKEN" -X POST "https://api.github.com/projects/columns/$COLUMN_ID/cards" -d "{\"content_id\":$ISSUE_ID,\"content_type\":\"Issue\"}"
