name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          python -m pip install -U sphinx sphinx-autodoc-typehints
          rm -rf docs
          sphinx-quickstart
          echo "master_doc = 'index'" >> conf.py
          echo "extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx_autodoc_typehints']" >> conf.py
          sphinx-apidoc -o . .
          make html
      - uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: build/html
