name: UI Automated Tests on MacOS

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  build-app:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Protobuf
        continue-on-error: true
        run: |
          brew update
          brew install protobuf 
          brew install cmake rustup-init gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav gst-rtsp-server gst-editing-services
      - name: Add Targets
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.7.1"
        run: |
          rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - name: Make Build for Appium to run
        continue-on-error: true
        run: |
          make dmg SIGNING_KEY=LOCAL
      - name: Install Uplink Desktop App
        run: |
          cp -r target/release/macos/Uplink.app /Applications/
      - name: Setup Node.js 🔨
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies 📦
        run: |
          cd appium-tests && npm install

      - name: Install and Run Appium Server 📱
        run: | ## try to uninstall first
          appium driver uninstall mac2
          chmod +x ./appium-tests/scripts/run_appium_macos_server.sh
          ./appium-tests/scripts/run_appium_macos_server.sh
      - name: Open Application for the first time
        run: open /Applications/Uplink.app

      - name: Take screenshot of GH runner
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: "desktop.jpg"

      - name: Quit Application before starting tests
        run: osascript -e 'quit app "Uplink.app"'
      - name: Run WebdriverIO tests on MacOS
        working-directory: ./appium-tests
        continue-on-error: true ## If driver already installed this prevents fail here
        run: |
          npm run mac.ci

      - name: Upload Screenshots if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-screenshots
          path: appium-tests/test-results/ios

      - name: Upload Appium Log if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-log
          path: appium-tests/appium.log
