name: UI Automated Tests on MacOS

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  build-app:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Protobuf
        continue-on-error: true
        run: |
          brew update
          brew install protobuf

      - name: Add Targets
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.7.1"
        run: |
          rustup target add x86_64-apple-darwin

      - name: Setup Node.js 🔨
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies 📦
        run: |
          cd appium-tests && npm install

      - name: Install and Run Appium Server 📱
        run: |
          chmod +x ./appium-tests/scripts/run_appium_macos_server.sh
          ./appium-tests/scripts/run_appium_macos_server.sh

      - name: Validations before starting appium
        run: |
          cd appium-tests/apps
          ls -la
          cd /Applications/
          ls -la

      - name: Open Application for the first time
        run: cargo run

      - name: Take screenshot of GH runner
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: "desktop.jpg"

      - name: Quit Application before starting tests
        run: osascript -e 'quit app "Uplink.app"'

      - name: Run WebdriverIO tests on MacOS
        working-directory: ./appium-tests
        run: npm run mac.ci

      - name: Upload Screenshots if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-screenshots
          path: appium-tests/test-results/ios

      - name: Upload Appium Log if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-log
          path: appium-tests/appium.log
