name: UI Automated Tests on MacOS

on:
  workflow_run:
    workflows: [Make dmg]
    types:
      - completed

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout working directory 🔖
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/appium-tests/apps/uplink_dmg.zip`, Buffer.from(download.data));

      - name: Unzip artifact
        working-directory: ./appium-tests/apps
        run: unzip uplink_dmg.zip

      - name: Setup Node.js 🔨
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies 📦
        run: |
          cd appium-tests && npm install

      - name: Install Uplink Desktop App
        run: |
          cd ./appium-tests/apps
          ls -la
          hdiutil attach ./appium-tests/apps/Uplink.dmg
          cp -r /Volumes/Uplink.dmg /Applications/
          hdiutil detach ./appium-tests/apps/Uplink.dmg

      - name: Install and Run Appium Server 📱
        run: |
          chmod +x ./appium-tests/scripts/run_appium_android_server.sh
          ./appium-tests/scripts/run_appium_macos_server.sh

      - name: Run WebdriverIO tests on MacOS
        run: npm run mac.ci

      - name: Upload Screenshots if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-screenshots
          path: appium-tests/test-results/ios

      - name: Upload Appium Log if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-log
          path: appium-tests/appium.log
