name: UI Automated Tests on MacOS

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  build-app:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: Install Protobuf
        continue-on-error: true
        run: |
          brew update
          brew install protobuf 
          brew install cmake rustup-init gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav gst-rtsp-server gst-editing-services
      - name: Add Targets
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13"
        run: |
          rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - name: Make Build for Appium to run
        run: |
          cargo update
          make dmg
      - name: Copy DMG to Appium Apps Directory
        working-directory: appium-tests/apps
        run: |
          ls -la
          unzip Uplink-Mac-Universal.zip
          cp -r target/release/macos/Uplink.app /Applications/
          sudo xattr -r -d com.apple.quarantine /Applications/Uplink.app

      - name: Setup Node.js 🔨
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies 📦
        run: |
          cd appium-tests && npm install

      #- name: Install Uplink Desktop App
      #  run: |
      #    cd ./appium-tests/apps
      #    ls -la
      #    hdiutil attach ./appium-tests/apps/Uplink.dmg
      #    cp -r /Volumes/Uplink.dmg /Applications/
      #    hdiutil detach ./appium-tests/apps/Uplink.dmg

      - name: Install and Run Appium Server 📱
        run: |
          chmod +x ./appium-tests/scripts/run_appium_macos_server.sh
          ./appium-tests/scripts/run_appium_macos_server.sh

      - name: Validations before starting appium
        run: |
          cd appium-tests/apps
          ls -la
          cd /Applications/
          ls -la

      - name: Run WebdriverIO tests on MacOS
        working-directory: ./appium-tests
        run: npm run mac.ci

      - name: Upload Screenshots if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-screenshots
          path: appium-tests/test-results/ios

      - name: Upload Appium Log if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-log
          path: appium-tests/appium.log
