name: UI Automated Tests on MacOS

on:
  workflow_run:
    workflows: ["Make dmg"]
    types: [completed]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout working directory 🔖
        uses: actions/checkout@v3

      - name: Download DMG from comments
        uses: suisei-cn/actions-download-file@v1.3.0
        id: uplink-dmg # Remember to give an ID if you need the output
        with:
          url: ${{ github.event.comment.body }}
          target: appium-tests/apps
          auto-match: true

      - name: Download DMG built during action 🗳️
        uses: actions/download-artifact@v3
        with:
          name: Uplink Universal Mac App
          path: appium-tests/apps

      - name: Setup Node.js 🔨
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies 📦
        run: |
          cd appium-tests && npm install

      - name: Install Uplink Desktop App
        run: |
          cd ./appium-tests/apps
          ls -la
          hdiutil attach ./appium-tests/apps/Uplink.dmg
          cp -r /Volumes/Uplink.dmg /Applications/
          hdiutil detach ./appium-tests/apps/Uplink.dmg

      - name: Install and Run Appium Server 📱
        run: |
          chmod +x ./appium-tests/scripts/run_appium_android_server.sh
          ./appium-tests/scripts/run_appium_macos_server.sh

      - name: Run WebdriverIO tests on MacOS
        run: npm run mac.ci

      - name: Upload Screenshots if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-screenshots
          path: appium-tests/test-results/ios

      - name: Upload Appium Log if tests failed 📷
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: appium-log
          path: appium-tests/appium.log
