[general]
theme = "default"
show_splash = true

[privacy]
satellite_sync_nodes = true
safer_file_scanning = true

[audiovideo]
noise_suppression = false

[extensions]
enable = true

[developer]
developer_mode = false
cache_dir = ".warp"
